export const colors = {
  light: {
    primary: "#3498DB",
    secondary: "#2C3E50",
    primaryBackground: "#F4F6F8",
    counterBackground: "#FFFFFF",
    plusBackground: "#3498DB",
    resetColor: "#E74C3C",
    plusColor: "#FFFFFF",
    vibrationColor: "#3498DB",
    text: "#2C3E50",
    border: "#BDC3C7",
    modalBackground: "#FFFFFF",
    modalText: "#2C3E50",
    SavedCountsBackground: "#FFFFFF",
    clearButton: "#E74C3C",
    itemBackground: "#F0F4F8",
  },

  dark: {
    primary: "#3498DB",
    secondary: "#FFFFFF",
    primaryBackground: "#121212",
    counterBackground: "#1E1E1E",
    plusBackground: "#3498DB",
    resetColor: "#E74C3C",
    plusColor: "#FFFFFF",
    vibrationColor: "#3498DB",
    text: "#FFFFFF",
    border: "#555555",
    modalBackground: "#424242",
    modalText: "#FFFFFF",
    SavedCountsBackground: "#1E1E1E",
    clearButton: "#E74C3C",
    itemBackground: "#2C2C2C",
  },
  primary: "#1a1a1a",
  secondary: "#FFFFFF",
};
