export const colors = {
  light: {
    primary: "#5E7D7E",
    secondary: "#E74C3C",
    primaryBackground: "#eecaca",
    counterBackground: "#dc9e9e",
    plusBackground: "#D5DBDB",
    resetColor: "#16A085",
    plusColor: "#16A085",
    vibrationColor: "#D4AC0D",
    text: "#333333",
    border: "#D5DBDB",
    modalBackground: "#FFFFFF",
    modalText: "#333333",
    SavedCountsBackground: "#FFFFFF",
    clearButton: "#efbfbf",
    itemBackground: "#faf6f6",
  },

  dark: {
    primary: "#FFFFFF",
    secondary: "#1a1a1a",
    primaryBackground: "#121212",
    counterBackground: "#FFB400",
    plusBackground: "#FFB400",
    resetColor: "#121212",
    plusColor: "#121212",
    vibrationColor: "#121212",
    text: "#FFFFFF",
    border: "#FFFFFF",
    modalBackground: "rgb(143,134,134)",
    modalText: "#FFFFFF",
    SavedCountsBackground: "#2a2828",
    clearButton: "#603838",
    itemBackground: "#3d3a3a",
  },
  primary: "#1a1a1a",
  secondary: "#FFFFFF",
};
